### ISSUE TITLE
Does not handle remote user types

### ISSUE THREAD

**Issue by queer** [dergraf/gen_json_schema#1]
Trying to generate a schema from a struct that uses a user type from a remote module fails with the below error. I would open a PR to fix it, but I sadly don't know enough about JSON schema to fix it :(

<details>
<summary>Error</summary>

    1) test greets the world (GenJsonSchemaTest)
      test/gen_json_schema_test.exs:4
      ** (FunctionClauseError) no function clause matching in GenJsonSchema.property_type/1

      The following arguments were given to GenJsonSchema.property_type/1:
      
          # 1
          {GenJsonSchema.Superhero.Biography, :t, []}
      
      Attempted function clauses (showing 9 out of 9):
      
          defp property_type({GenJsonSchema.Type, type, _opts})
          defp property_type({String, :t, []})
          defp property_type(:string)
          defp property_type(:atom)
          defp property_type(:integer)
          defp property_type(:float)
          defp property_type(:list)
          defp property_type(:nonempty_list)
          defp property_type(:range)
      
      code: |> GenJsonSchema.gen(:superhero)
      stacktrace:
        (gen_json_schema 0.1.0) lib/gen_json_schema.ex:168: GenJsonSchema.property_type/1
        (gen_json_schema 0.1.0) lib/gen_json_schema.ex:146: GenJsonSchema.type/1
        (gen_json_schema 0.1.0) lib/gen_json_schema.ex:43: anonymous fn/2 in GenJsonSchema.type/1
        (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
        (gen_json_schema 0.1.0) lib/gen_json_schema.ex:41: GenJsonSchema.type/1
        (gen_json_schema 0.1.0) lib/gen_json_schema.ex:17: GenJsonSchema.gen/2
        test/gen_json_schema_test.exs:12: (test)

</details>

<details>
<summary>Test case</summary>
Test module

    defmodule GenJsonSchema.Superhero do
      @moduledoc false

      @type powerstats :: %{
              intelligence: 0..100,
              strength: 0..100,
              speed: 0..100,
              durability: 0..100,
              power: 0..100,
              combat: 0..100
            }
      @type appearance :: %{
              gender: String.t() | nil,
              race: String.t() | nil,
              height: GenJsonSchema.Type.integer(minimum: 100, maximum: 1000),
              weight: GenJsonSchema.Type.integer(minimum: 1, maximum: 250),
              eyeColor: :green | :blue | :brown | :black | :white,
              hairColor: :no_hair | :white | :brown | :black | :blonde | :red
            }

      @type superhero :: %{
              id: non_neg_integer(),
              name: String.t(),
              slug: String.t(),
              powerstats: powerstats(),
              appearance: appearance(),
              biography: __MODULE__.Biography.t()
            }

      def gen() do
        GenJsonSchema.gen(__MODULE__, :superhero)
      end
    end

    defmodule GenJsonSchema.Superhero.Biography do
      @type t() :: %{
              fullName: String.t(),
              alterEgo: String.t(),
              aliases: [String.t()] | nil,
              placeOfBirth: String.t(),
              firstAppearance: String.t(),
              publisher: :marvel | :dc,
              alignment: :good | :bad
            }
    end

Test

    defmodule GenJsonSchemaTest do
      use ExUnit.Case

      test "it works" do
        GenJsonSchema.Superhero
        |> GenJsonSchema.gen(:superhero)
        |> IO.puts()
      end
    end

</details>

**Comment by dergraf** [comment]
Thanks for reporting. I have to look into this.
